apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sample-secret-pod
  name: sample-secret-pod
spec:
  containers:
  - image: nginx:1.18
    name: sample-secret-pod
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: sample-secret
          key: username
    volumeMounts:
    - name: sample-secret-volume
      mountPath: /mnt
  volumes:
  - name: sample-secret-volume
    secret:
      secretName: sample-secret
      items: 
      - key: password
        path: password.txt
        mode: 493 # 0755
